apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  cdro_run:
    steps:
      - uses: manav20052022/cdro_action@v0.1
        name: Run CDRO release pipeline
        with:
          url: http://34.148.237.21/flow
          username: ${{ secrets.CDRO_USERNAME }}
          user-token: ${{ secrets.CDRO_USER_TOKEN }}
          project-name: Default
          releaseh-name: dummyDoraMetricsRelease
          parameters: '{\"param1\":\"val1\",\"param2\":\"val2\"}'
