apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  cdro_run:
    steps:
      - uses: manav20052022/cdro_action@1.0
        name: Run CDRO release pipeline
        kind: build
        with:
          url: https://sda.preview.cb-demos.io/
          username: ${{ secrets.CDRO_USERNAME }}
          user-token: ${{ secrets.CDRO_USER_TOKEN }}
          project-name: mtyagi_Demo
          release-name: Awesome_Release
